---
title: "Post manipulating simulation results"
author: "Xinran Miao"
params:
  raw_data: "human_pancreas_norm_complexBatch.h5ad"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE}
rm(list = ls())
library(Rtsne)
library(plyr)      # mapvalues
library(scDesign2) # no
library(copula)    # corKendall
library(reshape2)  # melt
library(gridExtra) # arrangeGrob
library(ggpubr)    # as_ggplot
library(cowplot)   # draw_plot_label
#library(anndata)

library(tidyverse); theme_set(theme_bw());
```
```{r}
library(anndata)
ad <- read_h5ad("../../data/raw_data/human_pancreas_norm_complexBatch.h5ad")
```
```{r}
dat <- ad$X %>%
  as.data.frame() %>%
  as.matrix() %>%
  t()
colnames(dat) <- ad$obs$celltype

```


```{r}
obtain_para <- function(result_p,
                        base_dir = "../../results/simulation2/test/derived_data/human_pancreas_norm_complexBatch/") {
  ess_str <- substr(result_p, start = str_locate(result_p, pattern = base_dir)[2] + 1,
         stop = nchar(result_p))
  sp <- str_split(ess_str, "_") %>% unlist
  l <- list()
  if(sp[1] == "activated") {
    l$c_type <= "activated_stellate"
    l$cell_times <- sp[3] %>% as.numeric
  l$n_cell <- sp[4] %>% as.numeric
  l$seq_depth <- sp[5] %>% as.numeric
  } else{
    l$c_type <- sp[1]
    l$cell_times <- sp[2] %>% as.numeric
    l$n_cell <- sp[3] %>% as.numeric
    l$seq_depth <- sp[4] %>% as.numeric
  }
  
  return(l)
}
```
```{r}
c_type <- "multiple"
wrong_rs <- c()
for (c_type in c("acinar", "alpha", "beta", "delta", "ductal", "activated_stellate", "multiple")) {
  result_paths <- list.files("../../results/simulation2/test/derived_data/human_pancreas_norm_complexBatch",
                           full.names = TRUE, pattern = c_type)
  for(result_p in result_paths[c(3:4, 1:2)]) {
    if(result_p %in% wrong_rs) {
      next
    }
  # obtain simulation result
  sim_path <- list.files(result_p, pattern = "sim_count*", full.names = TRUE)
  fit_path <- list.files(result_p, pattern = "*fit*", full.names = TRUE)
  sim_result <- readRDS(sim_path)
  fit_result <- readRDS(fit_path)
  l <- obtain_para(result_p)
  
  # set idx_interest
  data_mat <- dat
  unique_cell_type <- names(table(colnames(data_mat)))
  set.seed(1)
  train_idx <- unlist(sapply(unique_cell_type, function(x){
  cell_type_idx <- which(colnames(data_mat) == x)
  n_cell_total <- length(cell_type_idx)
  sample(cell_type_idx, floor(n_cell_total/2))
  }))
  #traincount <- data_mat[, train_idx]
  #testcount <- data_mat[, -train_idx]
  load(str_c(result_p, "/train_idx.RData"))
  load(str_c(result_p, "/traincount.RData"))
  load(str_c(result_p, "/testcount.RData"))
  if(c_type == "multiple") {
    c_type <- table(colnames(data_mat)) %>% sort(decreasing = TRUE) %>%
    .[1:as.numeric(l$cell_times)] %>% names
    n_cell_new <- ncol(testcount[, colnames(testcount) %in% c_type])
    cell_type_prop <- table(colnames(testcount))[c_type]
    idx_interest <- c(1:length(ad$obs$celltype))[train_idx]
    idx_interest <- which(ad$obs$celltype[idx_interest] %in% c_type)
  } else {
    idx_interest <- c(1:length(ad$obs$celltype))[-train_idx]
  idx_interest <- which(ad$obs$celltype[idx_interest] %in% c_type)
  }
  
  
  
  
  
  # write h5ad file depending on how many cells are present in the derived data
  if(l$n_cell == 0) {
     #if(l$cell_times != 0) {
      #cat("parameter set wrong for ", result_p, "\n")
     # wrong_rs <- c(wrong_rs, result_p)
      #next
    #}
    derived_ad <-  AnnData(
    X = sim_result %>% as.matrix %>% t(),
    obs = data.frame(tech = ad$obs$tech[idx_interest],
                             celltype = colnames(sim_result),
                             size_factors = ad$obs$size_factors[idx_interest]),
    layers = list(
      spliced = matrix(0, nrow = ncol(sim_result), ncol = nrow(sim_result)),
      unspliced = matrix(0, nrow = ncol(sim_result), ncol = nrow(sim_result))
)
  )

  write_h5ad(derived_ad , filename = paste0(result_p, "/derived_ad.h5ad"))
  } else { # n_cell !=0
   if(l$cell_times == 0) {
      cat("parameter set wrong for ", result_p, "\n")
      wrong_rs <- c(wrong_rs, result_p)
      next
   } else {
     n_cell_new <- n_cell_new * l$n_cell}
    if(l$seq_depth != 0) {

    derived_ad <-  AnnData(
    X = sim_result %>% as.matrix %>% t(),
    obs = data.frame(tech = rep(ad$obs$tech[idx_interest], l$n_cell),
                             celltype = rep(ad$obs$celltype[idx_interest], l$n_cell),
                             size_factors = rep(ad$obs$size_factors[idx_interest]),
                     l$n_cell),
     layers = list(
      spliced = matrix(0, nrow = ncol(sim_result), ncol = nrow(sim_result)),
      unspliced = matrix(0, nrow = ncol(sim_result), ncol = nrow(sim_result)))
)
}

  write_h5ad(derived_ad , filename = paste0(result_p, "/derived_ad.h5ad"))
}
}

```




